import os
from telegram import Update
from telegram.ext import ContextTypes

from nova_ai.report_generator import generate_report
from memory.sessions import save_dataset, get_dataset, clear_dataset, save_report, get_report
from analyzers.csv_analyzer import CSVAnalyzer
from reports.pdf_generator import create_pdf

from utils.logger import Logger


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):

    message = """
👋 Welcome to *Nova AI Analyst*

Your AI-powered Business Intelligence Assistant.

I can help you:

📊 Upload any CSV dataset
🤖 Generate AI business insights
📈 Analyze sales & business performance
📑 Create executive reports
⚡ Deliver results directly in Telegram

Type /help to get started.
"""

    await update.message.reply_text(message,parse_mode="Markdown")

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    message = """
    📚 *Nova AI Analyst Commands*

    ━━━━━━━━━━━━━━━━━━

    🚀 /start
    Launch Nova AI Analyst

    ❓ /help
    Show this help menu

    ℹ️ /about
    About Nova AI Analyst

    ━━━━━━━━━━━━━━━━━━

    📂 Upload CSV
    Upload your dataset as a document

    📊 /stats
    View dataset statistics

    🧠 /analyze
    Generate AI business insights

    📄 /report
    Download the latest PDF report

    🗑 /clear
    Remove the uploaded dataset

    ━━━━━━━━━━━━━━━━━━

    Ready to analyze your business data 🚀
    """

    await update.message.reply_text(message,parse_mode="Markdown")


async def handle_document(update: Update, context: ContextTypes.DEFAULT_TYPE):
    document = update.message.document

    if document is None:
        await update.message.reply_text("❌ Please upload your CSV as a document.")
        return

    if not document.file_name.lower().endswith(".csv"):
        await update.message.reply_text("❌ Only CSV files are supported.")
        return

    file = await document.get_file()

    path = f"data/uploads/{document.file_name}"

    await file.download_to_drive(path)

    save_dataset(update.effective_user.id, path)

    Logger.info(
        f"Dataset uploaded: {document.file_name}"
    )

    await update.message.reply_text("✅ CSV uploaded successfully!\n\nNow type /analyze")


async def analyze(update: Update, context: ContextTypes.DEFAULT_TYPE):

    user_id = update.effective_user.id

    path = get_dataset(user_id)

    if path is None:
        await update.message.reply_text(
            "❌ Please upload a CSV file first."
        )
        return

    await update.message.reply_text("📂 Loading dataset...")

    analyzer = CSVAnalyzer(path)

    statistics = analyzer.generate_statistics()

    kpis = analyzer.get_kpis()

    date_info = analyzer.get_date_range()

    date_section = ""

    if date_info:
        date_section = f"""

        📅 *Date Range* ({date_info['column']})
        {date_info['start']} → {date_info['end']}
        ({date_info['days']} days)
        """

    if kpis["missing_values"] == 0:
        quality_section = (
            "🛡 *Data Quality*\n"
            "✅ Excellent (No missing values)"
        )
    else:
        quality_section = (
            f"🛡 *Data Quality*\n"
            f"⚠ {kpis['missing_values']} missing values detected"
        )

    await update.message.reply_text(
        f"""
    📊 *Business Snapshot*

    ━━━━━━━━━━━━━━━━━━

    💰 *Revenue* ({kpis.get('revenue_column', 'N/A')})
    ${kpis.get('total_revenue', 0):,.2f}

    📈 *Average Revenue*
    ${kpis.get('average_revenue', 0):,.2f}

    📦 *Total Records*
    {kpis.get('total_rows', 0)}
    
    🧾 *Total Columns*
    {kpis.get('total_columns', 0)}

    🏆 *Top Product* ({kpis.get('product_column', 'N/A')})
    {kpis.get('top_product', 'N/A')}

    🌍 *Top Location* ({kpis.get('region_column', 'N/A')})
    {kpis.get('top_region', 'N/A')}
    
    {date_section}

    {quality_section}
    """,
    parse_mode="Markdown"
    )

    await update.message.reply_text("🤖 Nova is analyzing your dataset...")

    progress = await update.message.reply_text(
        "⏳ AI analysis in progress...\n"
        "This may take up to a minute or more for larger datasets."
    )

    report = generate_report(statistics)

    await progress.delete()

    # Clean any Markdown generated by the AI
    report = report.replace("### ", "")
    report = report.replace("## ", "")
    report = report.replace("# ", "")
    report = report.replace("**", "")

    dataset_name = os.path.basename(path)

    pdf_path = create_pdf(report,f"report_{update.effective_user.id}.pdf", dataset_name)

    save_report(user_id, pdf_path)

    await update.message.reply_text(report)

    await update.message.reply_document(
        document=open(pdf_path, "rb"),
        filename="Executive_Report.pdf",
        caption="📄 Your Executive Business Report"
    )

    Logger.success(
        f"Analysis completed for user {user_id}"
    )


async def stats(update: Update, context: ContextTypes.DEFAULT_TYPE):

    user_id = update.effective_user.id

    path = get_dataset(user_id)

    if path is None:
        await update.message.reply_text(
            "❌ Please upload a CSV first."
        )
        return

    analyzer = CSVAnalyzer(path)

    analyzer.load_data()

    summary = analyzer.get_summary()

    columns = "\n".join(
        f"• {col}" for col in summary["column_names"]
    )

    missing = "\n".join(
        f"{k}: {v}"
        for k, v in summary["missing"].items()
    )

    numeric = ", ".join(summary["numeric_columns"])

    message = f"""
📊 *Dataset Statistics*

Rows: {summary["rows"]}
Columns: {summary["columns"]}

*Column Names*
{columns}

*Numeric Columns*
{numeric}

*Missing Values*
{missing}

✅ Dataset ready for AI analysis.
"""

    await update.message.reply_text(
        message,
        parse_mode="Markdown"
    )


async def clear(update: Update, context: ContextTypes.DEFAULT_TYPE):

    user_id = update.effective_user.id

    Logger.info(
        f"Dataset cleared for user {user_id}"
    )

    if get_dataset(user_id) is None:

        await update.message.reply_text(
            "📂 No dataset is currently loaded."
        )

        return

    clear_dataset(user_id)

    await update.message.reply_text(
        "🗑 Dataset cleared successfully!\n\n"
        "You can now upload another CSV."
    )

async def report(update: Update, context: ContextTypes.DEFAULT_TYPE):

    user_id = update.effective_user.id

    pdf_path = get_report(user_id)

    Logger.info(
        f"Report downloaded by user {user_id}"
    )

    if pdf_path is None:

        await update.message.reply_text(
            "❌ No executive report found.\n\nRun /analyze first."
        )

        return

    await update.message.reply_document(
        document=open(pdf_path, "rb"),
        filename="Executive_Report.pdf",
        caption="📄 Your Latest Executive Report"
    )


async def about(update: Update, context: ContextTypes.DEFAULT_TYPE):

    message = """
🤖 *Nova AI Analyst*

Version: *1.0*

AI-Powered Business Intelligence Assistant

━━━━━━━━━━━━━━━━━━

✨ *Features*

📊 CSV Dataset Analysis
🤖 AI Executive Reports
📄 PDF Report Export
📈 Dataset Statistics
🗑 Session Management

━━━━━━━━━━━━━━━━━━

🛠 *Built With*

• Python
• python-telegram-bot
• Pandas
• Ollama
• ReportLab

━━━━━━━━━━━━━━━━━━

👨‍💻 *Developer*

Edet Simon
"""

    await update.message.reply_text(
        message,
        parse_mode="Markdown"
    )



















